# Generated by Django 5.2.7 on 2025-11-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='bank_logo',
            field=models.ImageField(blank=True, null=True, upload_to='banks/'),
        ),
    ]
