# Generated by Django 5.2.7 on 2025-12-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='avatar_image',
            field=models.ImageField(blank=True, null=True, upload_to='store_avatar'),
        ),
        migrations.AlterField(
            model_name='store',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='store_background'),
        ),
    ]
