# Generated by Django 5.2.7 on 2025-12-10 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OptionGroupTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("is_required", models.BooleanField(default=False)),
                ("max_select", models.IntegerField(default=1)),
                ("position", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "option_group_templates",
                "ordering": ["position", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductOptionGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_required", models.BooleanField(blank=True, null=True)),
                ("max_select", models.IntegerField(blank=True, null=True)),
                ("position", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "option_group_template",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="product_links", to="products.optiongrouptemplate"),
                ),
                (
                    "product",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="template_groups", to="products.product"),
                ),
            ],
            options={
                "db_table": "product_option_groups",
                "ordering": ["position", "-created_at"],
                "unique_together": {("product", "option_group_template")},
            },
        ),
        migrations.CreateModel(
            name="OptionTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("position", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "option_group_template",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="options", to="products.optiongrouptemplate"),
                ),
            ],
            options={
                "db_table": "option_templates",
                "ordering": ["position", "-created_at"],
            },
        ),
    ]
