# Generated by Django 5.2.7 on 2025-12-25 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('shippers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='merchant_earning',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='shipper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='shippers.shipper'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipper_earning',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
