# Generated by Django 5.2.7 on 2025-12-26 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='productsimilarity',
            new_name='recommend_p_product_d5e4dc_idx',
            old_name='recommend_p_product__f3d0ad_idx',
        ),
        migrations.RenameIndex(
            model_name='userinteraction',
            new_name='recommend_u_user_id_cebde7_idx',
            old_name='recommend_u_user_id_75d9ab_idx',
        ),
        migrations.RenameIndex(
            model_name='userinteraction',
            new_name='recommend_u_product_6f55e7_idx',
            old_name='recommend_u_product__7ce35c_idx',
        ),
        migrations.RenameIndex(
            model_name='userinteraction',
            new_name='recommend_u_user_id_61e6e0_idx',
            old_name='recommend_u_user_id_67cf40_idx',
        ),
        migrations.AlterField(
            model_name='userinteraction',
            name='event',
            field=models.CharField(choices=[('store_view', 'Store view'), ('product_view', 'Product view'), ('add_to_cart', 'Add to cart'), ('purchase', 'Purchase'), ('store_favorite', 'Favorite store')], max_length=32),
        ),
    ]
