# Generated by Django 5.2.7 on 2025-12-03 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(choices=[('staff', 'Nhân viên'), ('cashier', 'Thu ngân'), ('manager', 'Quản lý ca'), ('delivery', 'Nhân viên giao hàng nội bộ')], default='staff', max_length=50)),
                ('status', models.IntegerField(choices=[(1, 'Đang hoạt động'), (2, 'Tạm dừng'), (3, 'Đã nghỉ việc')], default=1)),
                ('avatar_image', models.ImageField(blank=True, null=True, upload_to='employee_avatar/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='stores.store')),
            ],
            options={
                'db_table': 'employees',
                'ordering': ['-created_at'],
            },
        ),
    ]
