# Generated by Django 5.2.7 on 2025-12-25 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shippers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipper',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipper',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
